//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public string Store { get; set; }
        public string Cost { get; set; }
        public Nullable<System.DateTime> Removed { get; set; }
    }
}
